countrys_EU = {
    "Germany": {
        "country_name": "Germany",
        "population": 84482000,

        "X_market (Market / Economic Interdependence)": """ Germany is a highly developed industrial nation and the world's third-largest exporter. Its economy ranks first in Europe and third globally. Industrial structure and characteristics: (1) Emphasis on heavy industry. The automotive and mechanical engineering, chemical, and electrical sectors are pillar industries, while other manufacturing sectors such as food, textiles and apparel, steel processing, mining, precision instruments, optics, and aerospace are also well-developed. (2) Highly export-oriented. More than half of the products from major industrial sectors are sold abroad. In 2023, Germany's top five trading partners were China, the United States, the Netherlands, France, and Poland.
                                Automotive industry: The automotive industry is a crucial pillar of Germany's economy, accounting for 24% of its industrial output and providing one-seventh of the nation's jobs. The German automotive industry relies on both the Chinese market and the EU internal market. Imposing tariffs can protect the EU internal market.
                                The German Association of the Automotive Industry (VDA) represents the interests of over 600 international companies and 800,000 employees in Germany. The association includes passenger car, light and heavy commercial vehicle manufacturers, suppliers, as well as trailer and body manufacturers.
                                Employment and market size: Since 2021, the number of people employed in the automotive industry has continued to grow annually. Employees in the automotive industry support an industry worth €207.3 billion.,
                                Germany, the largest economy in Europe and the fifth-largest globally, competes with France for leadership within the EU. In the second quarter of 2022, Germany's GDP was €967.07 billion, growing quarter by quarter to reach €1,078.22 billion by the third quarter of 2024. However, the German economy faces pressures from energy transition and global supply chain instability, requiring the government to balance protecting domestic industries and maintaining international trade relations. Germany exhibits a high level of structural dependence on rare earth elements, primarily driven by its electric vehicle manufacturing sector.""",
        "X_political (Domestic Politics and Interest Mediation)": """ Germany's political stability index in 2023 was 8.03, indicating high stability. Its government operates efficiently, with robust rule of law and democratic institutions, with most indicators around 8.5. However, there are some controversies regarding immigration policies and energy transition, though these do not significantly affect the country's overall stability.
                                        The German Asia-Pacific Business Association (APA) is the most influential lobbying group in Sino-German relations. Before each visit of the German Chancellor to China, the APA submits a 'petition' on behalf of German businesses involved in China, reflecting their interests. The German public and some businesses prefer resolving issues through dialogue rather than confrontation, supporting the government's neutral stance in trade disputes.""" ,
        "X_institutional (Institutions, Diplomacy, and Path Dependence)": """ Germany is relatively supportive of globalization and free trade. Germany typically adopts a moderate stance in similar disputes, unwilling to take sides easily to avoid affecting long-term strategic relationships. Germany prefers resolving trade disputes through dialogue and negotiation, avoiding measures that could lead to prolonged conflicts.,
                                   According to international organization forecasts, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025.
                                   Despite slowing growth, global trade is generally on an upward trend. Below is a specific summary of the current situation: Trade protectionism challenges: Tariff and non-tariff barriers are rising, especially in developed countries and some developing nations. For example, the United States has imposed high tariffs on Chinese electric vehicles and other goods.
                                   Geopolitical impacts: The Russia-Ukraine conflict affects the global economy through supply chains, increasing trade uncertainty. Global electric vehicle market: In 2023, global electric vehicle sales reached approximately 14 million units, expected to rise to 17 million by the end of 2024. China, the United States, and Europe are the main production and consumption markets, with China's market share expected to remain at 40% by 2030.
                                   U.S. tariff policy on China: Starting September 2024, the U.S. imposed a 100% tariff on Chinese electric vehicles. China's response: Strengthening independent innovation and improving compliance efforts to mitigate tariff impacts.
                                   Sino-European relations: Facing challenges such as regional security and human rights issues, while also being influenced by Russia, the United States, and other factors. Nonetheless, there remains room for cooperation between China and Europe in areas such as trade and global governance.
                                   Germany aims to maintain 'critical solidarity.' **Germany needs to respect the European Commission's investigation report and uphold EU unity.** The current government advocates for EU unity and Franco-German coordination, supports European integration, and enhances European strategic autonomy. As the largest economy in the EU, Germany's influence in political decision-making is significant. In areas such as EU economic policy formulation and regional coordinated development, Germany's opinions often play a key role. Its rigorous decision-making style and strong economic foundation mean that many projects and policies related to EU development require Germany's support and participation to be effectively implemented. Germany is committed to building a 'European Germany,' aligning national interests with regional integration to serve its core interests.
                                   China is the largest single market for Mercedes-Benz, Volkswagen, and BMW, accounting for approximately one-third of their total sales.Automotive exports account for approximately 15% of Germany's total exports, with the Chinese market representing nearly 40% of its global sales (e.g., Volkswagen's sales in China exceed 50%). In March 2014, Sino-German relations were elevated to a comprehensive strategic partnership. Germany is a member of the EU and NATO, traditionally viewing the EU and transatlantic relations with the United States as core pillars of its foreign policy. The current government advocates for EU unity and Franco-German coordination, supports European integration, and enhances European strategic autonomy. Germany tends to adopt a balanced stance in Sino-European trade disputes.
                                  Germany’s FDI to China was 6433.82 billion Dolor in 2023 and 4896.17 billion in 2024; China’s FDI to Germany amounted to 530.93 billion in 2023 and 74.63 billion in 2024.Joint Ventures include Zollner Electronics (Taicang) Co., Ltd, Zhejiang Demai Machinery Co., Ltd, Bosch Hydrogen Power Systems (Chongqing) Co.,, among others. """ ,
 },
    "France": {
        "country_name": "France",
        "population": 68170000,
        "X_market (Market / Economic Interdependence)": """France has been a strong advocate for related measures and was the country that pushed the EU to initiate a so-called 'anti-dumping investigation' against Chinese electric vehicles.
                                Automotive industry: The French automotive industry underwent significant changes with the 2021 merger of Fiat Chrysler Automobiles and PSA Group, forming Stellantis, now the world’s fourth-largest automaker. However, the industry faced challenges such as the COVID-19 pandemic and semiconductor shortages, which reduced production to 1.35 million vehicles in 2021, far below pre-pandemic levels. 
                                Despite these setbacks, the sector remains vital to France’s economy, contributing 10.1% to total goods exports in 2020. Electric vehicles (EVs) play a growing role in the market. In 2021, battery electric vehicles (BEVs) and plug-in hybrids accounted for 18.27% of car sales, with Renault outperforming Tesla in BEV sales by about 6,000 units. Nevertheless, internal combustion engine vehicles continued to dominate, with petrol and diesel cars making up 61.31% of sales.
                                Environmental concerns are driving the shift to EVs, but consumer adoption is hindered by inadequate information. 
                                As of November 2021, 63% of French consumers felt poorly informed about EV costs compared to petrol or diesel cars, and 54% lacked understanding of their environmental benefits. Transportation remains France's largest source of CO2 emissions, contributing 126 million metric tons in 2021. The transition to zero-emissions vehicles is crucial for reducing the industry’s environmental impact.
                                The French Finance Minister stated: 'The automotive industry is part of our industrial culture, and this industry is facing a once-in-a-century transformation. Due to fierce competition from other countries, especially China, our transition is difficult, so we need unity in this industry. Europe must adopt trade policies to protect our industry, jobs, and technology.'
                                Brandy industry: France is renowned for its brandy exports, particularly Cognac. In 2022, approximately 212.5 million bottles of Cognac were sold, with 97.2% exported to leading markets such as the United States, China, and other European countries. This indicates that the United States and China are among the top destinations for French brandy exports.
                                France's GDP in Q2 2022 was €659.2477 billion, rising to €693.8005 billion by Q3 2023, and gradually increasing to €721.6340 billion by Q3 2024, showing steady growth.France exhibits a high level of structural dependence on rare earth elements, primarily driven by its aerospace and defense industries. """,
        "X_political (Domestic Politics and Interest Mediation)":"""France's political stability index is 7.45, indicating relatively high stability. Despite strong democratic and legal institutions, frequent protests (e.g., the 'Yellow Vest Movement') and social divisions have impacted social order in recent years.""",
        "X_institutional (Institutions, Diplomacy, and Path Dependence)": """France holds a somewhat skeptical attitude toward globalization and free trade. France established diplomatic relations with China on January 27, 1964, becoming the first Western major power to formally recognize China. Since then, bilateral relations have generally developed smoothly.
                                   According to international organizations, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025.
                                   Despite slowing growth, global trade is generally on an upward trend. Specific summaries of the current situation include: Trade protectionism challenges: Rising tariffs and non-tariff barriers, especially in developed and some developing countries. For example, the U.S. has imposed high tariffs on Chinese electric vehicles.
                                   Geopolitical impacts: The Russia-Ukraine conflict affects the global economy through supply chains, increasing trade uncertainty. Global electric vehicle market: In 2023, global electric vehicle sales were approximately 14 million units, expected to reach 17 million by the end of 2024. China, the U.S., and Europe are the main production and consumption markets, with China's market share expected to remain at 40% by 2030.
                                   U.S. tariff policy on China: Starting September 2024, the U.S. imposed a 100% tariff on Chinese electric vehicles. China's response: Strengthening independent innovation, improving compliance, and mitigating tariff impacts.
                                   Sino-European relations: Facing challenges in regional security and human rights, influenced by factors such as Russia and the U.S. Despite this, there is still room for cooperation in trade and global governance.
                                  France is a permanent member of the UN Security Council, a founding member of the EU, and a NATO member. It hosts the headquarters of important international and regional organizations such as UNESCO, Interpol, OECD, and the European Parliament. On the EU political stage, France plays a central role. With its profound historical and cultural heritage, strong diplomatic influence, and independent political decision-making system, France often leads in major international affairs and EU policy-making. For example, in promoting EU foreign policy adjustments and cultural exchange cooperation, France actively contributes wisdom and strength, striving to enhance the EU's voice and cultural soft power on the international stage. At the same time, France has a firm stance and active advocacy on issues such as European defense construction, advocating for increased EU military autonomy and reduced external military dependence.
                                   France's trade with China in 2022 was €72.908 billion, declining by 8.04% to €67.049 billion in 2023. From January to September 2024, Sino-French bilateral trade was $59.238 billion, down 1.2% year-on-year, with Chinese exports at $33.390 billion, up 5.3%, and imports at $25.847 billion, down 8.6%.
                                    France’s FDI to China was 822.88 billion Dolor in 2023 and -213.07 billion in 2024; China’s FDI to France amounted to 64.88 billion in 2023 and -77.87 billion in 2024. Joint ventures include Airbus (Tianjin) Final Assembly Co., Ltd., Taishan Nuclear Power Joint Venture Co., Ltd., and Dynasty Wine Ltd. (a Sino–French joint venture), among others.""",
 },
    "Italy": {
        "country_name": "Italy",
        "population": 58856000,

        "X_market (Market / Economic Interdependence)": """Italy is a developed industrial country, the third-largest economy in the EU and the eighth-largest in the world. Regional economic development is uneven, with the north being industrially and commercially advanced, while the south is primarily agricultural and economically lagging. Key economic indicators for 2023 are as follows: GDP: €2.09 trillion, fiscal deficit rate: 7.2%, unemployment rate: 7.6%. Italy has a robust real economy and is the second-largest manufacturing power in the EU after Germany.
                                    Italy holds a significant share in the global market for medium-tech consumer and investment goods, though high-tech products are relatively fewer. Major industries include: petrochemicals, automotive manufacturing, household appliances, electronic instruments, metallurgy, machinery, equipment, textiles, clothing, leather, furniture, food, beverages, tobacco, paper, publishing, printing, and construction. Small and medium-sized enterprises (SMEs) are highly specialized, adaptable, and traditionally export-oriented, with strong international competitiveness in sectors such as leather, footwear, clothing, textiles, furniture, kitchenware, tiles, silk, jewelry, winemaking, machinery, marble extraction, and mechanical engineering. The service sector has grown rapidly and remains on an upward trajectory, playing a vital role in the national economy, accounting for two-thirds of GDP. Most services are related to the marketing or supply of manufactured goods. Tourism is highly developed, making Italy the fourth-largest tourist destination globally. Major tourist cities include Rome, Venice, and Florence, with around 320,000 people employed in the tourism sector.
                                    Italy is a traditional agricultural powerhouse globally, renowned for the quality of its olive oil, wine, tomato sauce, and other agricultural products.
                                    Automotive industry: Italy was once a global leader in the automotive industry, though its position in the passenger car market has declined, primarily dominated by Fiat. However, Italy remains a leader in luxury and supercar manufacturing, with brands like Ferrari, Lamborghini, and Maserati experiencing significant growth. For example, Ferrari shipped over 10,000 vehicles in 2019, and Lamborghini's vehicle deliveries increased sixfold over the past decade. From 2017 to 2019, the electric vehicle market accounted for only 0.6% of the total market.
                                    Industry scale: The Italian automotive industry is a core engine of manufacturing, with over 5,000 companies, an annual output value of €90 billion, and employing 330,000 people, making it one of the leading automotive manufacturing countries in the EU. Supply chain advantage: Italy is the second-largest automotive component supplier after Germany, with over 200 component production companies covering the entire supply chain from design to vehicle production. 50% of automotive component production is exported, with extensive collaboration with global OEMs (e.g., Stellantis). Production bases: Italy has multiple automotive production bases, covering engine and battery production, with renowned companies such as Ferrari and Lamborghini.
                                    Market data: Italy produces 1 million vehicles annually, making it the third-largest automotive market in Europe. Industry development: The Italian automotive industry focuses on luxury and high-performance vehicles, with well-known brands like Ferrari and Lamborghini. In recent years, influenced by the global electrification trend, Italian automakers have ventured into the new energy vehicle market, with Fiat Chrysler Group launching several electric models. Typical company market data: In 2022, Italy produced approximately 1.5 million vehicles, a 5% year-on-year decrease. New energy vehicles accounted for about 10% of production, showing an upward trend. Sales of luxury brands like Ferrari and Lamborghini remained stable and growing.
                                    Dairy industry: In 2023, France was the main destination for Italy’s dairy product exports. Data from that year showed that the value of dairy products exported from Italy to France reached nearly €1.2 billion. Germany and the United States were the second and third major destinations for Italy’s dairy product exports, respectively.
                                    Huge deficits and public debt have long been two major challenges for Italy's economy. In 2011, affected by the international financial crisis and the Greek sovereign debt crisis, Italy's sovereign debt situation became severe, and the economy remained sluggish. Italy experienced three recessions in 2008, 2012-2014, and 2019-2020. In 2023, the fiscal deficit rate was 7.2%, with public debt totaling approximately €2.86 trillion, accounting for 137.3% of GDP. The average cost of automotive manufacturing in Italy is higher than that of Stellantis' factories in other countries. This year, Stellantis has gradually shifted production capacity, supply chain procurement, and human resources from Italy to lower-cost regions and expanded related businesses. Under these circumstances, Italian factories may face the risk of at least 12,000 job cuts, and local component suppliers could also face additional large-scale layoffs.""",
        "X_political (Domestic Politics and Interest Mediation)":"""Italy's political stability index is 6.90, indicating moderate stability. The country experiences significant political turmoil and frequent government changes. Economic crises and social discontent have adversely affected government stability. Although the rule of law and democratic institutions are relatively well-established, policy continuity is lacking.""",
        "X_institutional (Institutions, Diplomacy, and Path Dependence)": """Italy holds a somewhat skeptical attitude toward globalization and free trade. After World War II, Italy participated in the Marshall Plan, signed the North Atlantic Treaty, and actively engaged in European integration, becoming one of the founding members of the EU. Italy established diplomatic relations with China on November 6, 1970. In June 1985, both countries opened consulates general in Milan and Shanghai, respectively. In June 1998, China opened a consulate general in Florence, and in November, Italy opened one in Guangzhou. In 2014, Italy opened a consulate general in Chongqing. Since establishing diplomatic relations, the two countries have developed friendly cooperation in various fields. In 2004, they established a comprehensive strategic partnership.
                                    According to international organization forecasts, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025.
                                   Despite slowing growth, global trade is generally on an upward trend. Specific summaries of the current situation include: Trade protectionism challenges: Tariff and non-tariff barriers are rising, especially in developed and some developing countries. For example, the U.S. has imposed high tariffs on Chinese electric vehicles and other goods.
                                   Geopolitical impacts: The Russia-Ukraine conflict has affected the global economy through supply chains, increasing trade uncertainty. Global electric vehicle market: In 2023, global electric vehicle sales reached approximately 14 million, expected to reach 17 million by the end of 2024. China, the U.S., and Europe are the main production and consumption countries, with China's market share expected to remain at 40% by 2030.
                                   U.S. tariff policy on China: Starting September 2024, the U.S. imposed a 100% tariff on Chinese electric vehicles. China's response: Strengthening independent innovation and improving compliance to mitigate tariff impacts.
                                   China-EU relations: Facing challenges in regional security and human rights, while influenced by factors such as Russia and the U.S. Nevertheless, there is still room for cooperation between China and the EU in trade and global governance.
         As one of the founding members of the EU, successive Italian governments have highly valued and actively promoted European integration. As an EU member, Italy benefits from the single market, allowing seamless exports to other member states, especially in its dominant industries such as luxury goods, automobiles, and agricultural products. Italy receives substantial economic support from the EU and must safeguard the EU's unified interests. In 2020, Italy's economy was severely impacted by the COVID-19 pandemic, receiving €209 billion from the EU Recovery Fund, accounting for 28% of the total fund. The European Commission approved Italy's recovery plan in June 2021, disbursing €24.9 billion in April 2022, €21 billion in July 2022, €18.5 billion in October 2023, and €16.5 billion in November 2023. Italy believes that EU integration is an effective means to address global challenges, and only a strong and united EU can best protect Italy's security and interests. Italy supports EU institutional reforms and actively participates in the establishment and operation of the European External Action Service. After the European sovereign debt crisis, Italy proposed establishing a unified crisis response fund within the EU, supporting the EU's three major economic governance measures: unified European debt issuance, granting the European Central Bank greater powers, and enhancing coordination of structural reforms.
   China policy: Since taking office, Meloni has faced political pressure within the EU and has supported the EU's tough stance on anti-dumping policies, voting in favor of key issues. Foreign trade is a major pillar of Italy's economy,accounting for over 40% of GDP. Consumer goods, machinery, and services hold significant positions in the international market. In 2023, Italy's total exports were €626.17 billion, unchanged from the previous year, while imports totaled €591.716 billion, a 10.4% year-on-year decrease. Italian products are highly competitive internationally, with a wide range of export goods, primarily including machinery, vehicles, agricultural products, steel, chemicals, pharmaceutical s, household appliances, clothing, footwear, and precious metals. The EU is Italy's main export market, accounting for over 50% of total exports.
    Italy’s FDI to China was -769.52 billion Dolor in 2023 and 354.62 billion in 2024; China’s FDI to Italy amounted to 343.63 billion in 2023 and 528.87 billion in 2024. Joint ventures include SAIC-IVECO Hongyan Commercial Vehicle Co., Ltd., Shandong BorgWarner Friction Materials Technology Co., Ltd., and Shaoxing OLI–Wolong Vibration Machinery Co., Ltd., among others.
     Italy-China trade in 2022 was €74.287 billion, declining to €67.822 billion in 2023, a decrease of 8.70%. China's main exports to Italy include clothing, textiles, footwear, travel goods, cashmere, toys, data processing equipment, plastics, and pharmaceuticals. China's main imports from Italy include textile machinery, animal leather, TV tubes, metalworking machinery, rubber or plastic processing machinery, pharmaceuticals, tobacco processing machinery, molds, and components for TVs, radios, and communication equipment. Italy's automotive exports to China account for a very low percentage of total exports, roughly between 0.02% and 0.2% (based on 2023 estimates). Automotive products are not a major category of Italy's exports to China, which are concentrated in pharmaceuticals, textiles, and machinery. Additionally, Italy's automotive exports are highly dependent on the European market, with limited exports to China.""",

},
    "Netherland": {
    "country_name": "Netherland",
        "population": 17940000,

    "X_market (Market / Economic Interdependence)": """The Netherlands has an export-oriented economy, with 80% of raw materials imported and over 60% of products exported. 80% of foreign trade is conducted within the EU. Exports of goods and services account for 32.6% of GDP. The Netherlands is technologically advanced in electronics, chemicals, water management, shipbuilding, and food processing, with a well-developed financial services and insurance industry. Land, sea, and air transportation are highly convenient, making the Netherlands a key transportation hub in Europe. Agriculture is highly intensive, with agricultural exports ranking among the top globally. In 2023, the Dutch economy grew by 0.1%, with GDP exceeding €1 trillion for the first time.
                                The Netherlands has a well-developed industrial sector, with major industries including food processing, petrochemicals, metallurgy, mechanical engineering, electronics, steel, shipbuilding, printing, and diamond processing. It is one of the world's leading shipbuilding nations. Rotterdam is Europe's largest oil refining center. Since the 1980s, the Dutch government has actively encouraged the development of emerging industries, particularly high-tech sectors such as space, microelectronics, and life sciences.
                                The Netherlands is a global leader in dairy production and the world's largest exporter of flowers.
                                The service sector is a pillar of the national economy, focusing on logistics, banking, insurance, tourism, and legal services.
                                Automotive industry: The Dutch electric vehicle industry is a key driver of future economic growth. Without protection, it may face a decline similar to the solar panel industry. Maintaining the competitiveness of the domestic electric vehicle industry is essential to avoid economic losses from unfair competition. For example, in 2023, the sales value of the Dutch automotive manufacturing industry reached billions of euros, accounting for a significant proportion of the total manufacturing output. Considering the overall economic scale and industrial structure of the Netherlands, this achievement is remarkable. Additionally, the Dutch automotive manufacturing industry has strong capabilities in technological innovation and product development, providing robust support for the industry's sustainable development. The Dutch automotive industry employs approximately 100,000 people, generating at least €90 billion in annual revenue.
                                In the Dutch electric vehicle market, the sales shares of brands from different countries are as follows: U.S. 22%; Sweden 12%; South Korea 4%; Germany 6.7%; France 3.7%; China 5.6%; Czech Republic 7%.
                                Pork exports: In 2023, the proportion of Dutch pork exports to China significantly decreased. The main destinations for Dutch pork exports are Italy (€377 million), Germany (€324 million), Greece (€229 million), and South Korea (€199 million). Between 2021 and 2022, the fastest-growing markets for Dutch pork exports were Italy (€59.4 million), Poland (€55.8 million), and Greece (€36.4 million).
                                The Netherlands is the third-largest exporter in the eurozone, with over two-thirds of GDP coming from goods trade. Major export goods include machinery and transport equipment (28% of total exports), mineral fuels (23%), food (11%), apparel and footwear (10%), and pharmaceutical products (5%). Over 60% of exports are sent to EU countries. Major trading partners include Germany (24% of total exports), Belgium (12%), France (9%), the UK (8%), the U.S., Italy, and Japan. The Netherlands' exports to China account for a low proportion, around 2%, ranking 11th, indicating low dependence on trade with China.
                                In 2023, the fiscal deficit accounted for 0.3% of GDP, below the EU's 3% threshold, while government debt accounted for 45.6% of GDP, below the EU's 60% warning line. In Q2 2022, the Netherlands' GDP was €251.303 billion, growing slightly to €280.448 billion by Q3 2024. Overall growth is stable but modest.""",

    "X_political (Domestic Politics and Interest Mediation)": """The Netherlands' political stability index in 2023 was 8.10, indicating high stability. Its political and social environment is stable, with efficient government operations, extremely low corruption, and highly mature rule of law and democratic institutions. Although there are occasional small-scale social protests, overall stability remains largely unaffected.""",
    "X_institutional (Institutions, Diplomacy, and Path Dependence)": """The Netherlands is relatively supportive of globalization and free trade. The Netherlands established diplomatic relations with China at the chargé d'affaires level in November 1954, upgrading to ambassadorial level on May 18, 1972. In May 1981, due to the Dutch government's approval of submarine sales to Taiwan, diplomatic relations were downgraded to the chargé d'affaires level. On February 1, 1984, Sino-Dutch relations were restored to ambassadorial level.
          According to international organizations, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025.
                               Despite slowing growth, global trade is generally on an upward trend. Specific summaries of the current situation include: Trade protectionism challenges: Rising tariffs and non-tariff barriers, especially in developed and some developing countries. For example, the U.S. has imposed high tariffs on Chinese electric vehicles.
                               Geopolitical impacts: The Russia-Ukraine conflict affects the global economy through supply chains, increasing trade uncertainty. Global electric vehicle market: In 2023, global electric vehicle sales were approximately 14 million units, expected to reach 17 million by the end of 2024. China, the U.S., and Europe are the main production and consumption markets, with China's market share expected to remain at 40% by 2030.
                               U.S. tariff policy on China: Starting September 2024, the U.S. imposed a 100% tariff on Chinese electric vehicles. China's response: Strengthening independent innovation, improving compliance, and mitigating tariff impacts.
                               Sino-European relations: Facing challenges in regional security and human rights, influenced by factors such as Russia and the U.S. Despite this, there is still room for cooperation in trade and global governance.
   The Netherlands is a founding member of the EU and NATO. National security, economic interests, and democratic human rights are the three pillars of its foreign policy. The Netherlands views the U.S. as a traditional ally, actively participates in EU affairs, values the role of international organizations such as the UN, and engages in multilateral affairs. It was elected as a non-permanent member of the UN Security Council in 2018. As a founding member of the EU, the Netherlands respects the decisions of the European Commission.
Netherlands’s FDI to China was 3149.87 billion Dolor in 2023 and -7274.50 billion in 2024; China’s FDI to  Netherlands amounted to 2214.53 billion in 2023 and 5665.15 billion in 2024. Joint ventures include Beijing Zhongke Robin Radar Technology Co., Ltd., Vopak (Shanghai) Management Co., Ltd., and ASML’s China-related joint operations, among others.""",
},
    "Spain": {
        "country_name": "Spain",
        "population": 48590000,

        "X_market (Market / Economic Interdependence)": """
            Spain is a developed industrial country, with its economy ranking 4th in the EU and 15th in the world. The agriculture, industry, and service sectors account for 2.3%, 20.8%, and 67.9% of GDP, respectively. After the 2008 international financial crisis and the European debt crisis, the economy suffered severe impacts but achieved restorative growth in 2014, with growth rates among the highest in the EU. By 2016, GDP had surpassed pre-crisis levels. In 2023, the GDP reached 1.46 trillion euros, a year-on-year increase of 2.5%, marking the third consecutive year above the eurozone average. Major industrial sectors include food and beverages, automotive, power, chemicals, metal products, oil refining, steel, rubber, plastic products, machinery manufacturing, and non-metallic mineral products. Textiles, shipbuilding, aerospace, and pharmaceuticals also contribute significantly.
            Spain is a major automobile producer and exporter in the EU. In 2023, automobile production reached approximately 2.4 million units, a 13.4% increase year-on-year, ranking 2nd in the EU and 8th globally. Exports totaled 1.881 million vehicles, a 3.3% increase, with 70% of exports going to other EU countries.
            Automotive Industry: The automotive industry is one of the pillars of Spain's national economy. A major automobile producer and exporter within the European Union. In 2023, the country's automobile production reached approximately 2.4 million units, marking a 13.4% year-on-year increase, ranking it second in the EU and eighth globally. The export of automobiles stood at 1.881 million units, up by 3.3% compared to the previous year, with 70% of these exports destined for other EU countries.In 2022, the added value created by automobile and parts production accounted for about 8.1% of Spain's GDP, with employment representing 9% of the labor force. Spain produced about 2.4 million vehicles, a 13.4% increase, ranking 2nd in the EU and 8th globally. Exports accounted for 75% of production, with 1.881 million vehicles exported, mainly to other EU countries. Automobiles and parts are among Spain's largest export commodities, with exports nearing 54 billion euros in 2023, accounting for 15% of total merchandise exports. Traditional fuel vehicles still dominate, representing 53% of new vehicle registrations in 2023, while hybrid vehicles (including both hybrid and plug-in hybrid) accounted for 32%. European brands dominate the Spanish market, holding about 70% of the market share, with major brands including Toyota, Volkswagen, Renault, Hyundai, Kia, and Peugeot.
            Pork Industry: Spain is a leading exporter of pork in Europe, with exports valued at 6.8 billion U.S. dollars in 2023. The country's pork export value has shown significant growth, reaching 6.3 billion euros in 2023, a 10.56% increase from the previous year. While specific data on the top export destinations for Spanish pork products is limited in the provided information, some insights can be gleaned from older data on raw ham exports. In 2019, the main recipients of Spanish raw ham were France (24.7%), Germany (23.8%), Portugal (9.7%), and Italy (6%).
            Exports: In 2022, Spain exported $5.92B in Pig Meat, making it the 1st largest exporter of Pig Meat in the world. At the same year, Pig Meat was the 7th most exported product in Spain. The main destination of Pig Meat exports from Spain are: China ($1.05B), Japan ($729M), France ($524M), South Korea ($455M), and Italy ($407M). The fastest growing export markets for Pig Meat of Spain between 2021 and 2022 were Japan ($112M), Italy ($108M), and Romania ($89.1M).
            Major imports include petroleum, chemical products, fuels, and electrical equipment; major exports include automobiles and parts, machinery, chemical products, and agricultural and food products. Key trading partners are the EU, Asia, Latin America, and the United States.
         In the second quarter of 2022, Spain's GDP was 343,673.0 million euros, growing to 393,263.0 million euros by the third quarter of 2024, showing slow but steady growth. The inflation rate is 3.1%, the unemployment rate is 11.76%, public debt stands at 1.54 trillion euros, and the public deficit accounts for 3.66%. Spain's automotive industry faces challenges such as global economic fluctuations, rapid technological iterations, and supply chain stability. Additionally, the electrification of automobiles is progressing relatively slowly.
        """,
        "X_political (Domestic Politics and Interest Mediation)": """
            Spain's political stability index is 7.60, indicating a relatively high level of stability. Although the issue of Catalan independence persists and occasionally causes social unrest, the overall political and social environment remains relatively stable. The government performs well in operational efficiency and corruption control, but public protests still occur from time to time.
        """,
        "X_institutional (Institutions, Diplomacy, and Path Dependence)": """
             Spain holds a somewhat skeptical attitude toward globalization and free trade. Spain established diplomatic relations with China on March 9, 1973, and the two countries established a comprehensive strategic partnership in November 2005.
            According to international organization forecasts, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025. Despite slowing growth, global trade is generally on an upward trend. Specific summaries of the current situation include:
            Trade Protectionism Challenges: Rising tariffs and non-tariff barriers, especially in developed countries and some developing countries. For example, the U.S. has imposed high tariffs on Chinese electric vehicles and other goods.
            Geopolitical Impacts: The Russia-Ukraine conflict affects the global economy through supply chains, increasing trade uncertainty.
            Global Electric Vehicle Market: Global electric vehicle sales reached approximately 14 million units in 2023 and are expected to reach 17 million by the end of 2024. China, the U.S., and Europe are the main producers and consumers, with China's market share expected to remain at 40% by 2030.
            U.S. Tariff Policies on China: Starting September 2024, the U.S. will impose a 100% tariff on Chinese electric vehicles.
            China's Response Measures: Strengthening independent innovation and improving compliance efforts to mitigate the impact of tariffs.
            China-EU Relations: Facing challenges in regional security and human rights issues, influenced by factors such as Russia and the U.S. Nevertheless, there is still room for cooperation between China and the EU in areas such as trade and global governance.
            To the west, it borders Portugal, and to the northeast, it adjoins France and Andorra.Spain is a member of the EU, NATO, OECD, and a permanent guest of the G20. It pursues Europeanism and emphasizes EU institutional development. Spain highly values its relationship with the U.S. and considers Europe the primary pillar of its foreign policy, striving to play a greater role within the EU and supporting EU strategic autonomy. Following the COVID-19 pandemic, Spain became the second-largest beneficiary of the EU Recovery Fund, eligible for up to 140 billion euros in grants and loans. By the end of 2023, Spain had received 37.04 billion euros from the EU Recovery Fund. Spain held the EU rotating presidency in the second half of 2023 and views its relationship with the U.S. as a key diplomatic pillar.
         Spain pursues Europeanism and emphasizes EU institutional development. In 2023, Spain's total import and export value of goods was 826.33 billion euros, with imports at 435.17 billion euros and exports at 391.16 billion euros, resulting in a trade deficit of 44.01 billion euros. Major imports include petroleum, chemical products, fuels, and electrical equipment; major exports include automobiles and parts, machinery, chemical products, and agricultural and food products. Key trading partners are the EU, Asia, Latin America, and the United States. Spain is China's fifth-largest trading partner within the EU, while China is Spain's largest trading partner outside the EU. Bilateral trade between Spain and China was 50.095 billion euros in 2022 and 44.205 billion euros in 2023, a year-on-year decrease of 11.76%. China's main exports to Spain include textiles, machinery, chemicals, and light industrial products; China's imports from Spain, totaling 8.87 billion U.S. dollars, a 9.1% decrease, primarily include pork, machinery, transportation equipment, plastic products, minerals, and pharmaceuticals.
         Spain’s FDI to China was 262.76 billion Dolor in 2023 and -1174.56 billion in 2024;China’s FDI to Spain amounted  to - 1174.56 billion in 2023 and 201.17 billion in 2024.Joint ventures include the CATL–Stellantis power battery joint venture plant, Chery Automobile’s joint venture manufacturing project in Spain, and China Tobacco Moddy (Jiangmen) Paper Co., Ltd., among others.""",
},
    "Denmark": {
        "country_name": "Denmark",
        "population": 3903000,

        "X_market (Market / Economic Interdependence)": """Population: 5.946 million (December 2023), with Danes accounting for about 85%. The official language is Danish. Approximately 74% of the population adheres to the Lutheran Church of Denmark. GDP: about $405 billion. Industry plays a significant role in the national economy, with industrial output accounting for about 34.5% of GDP (2022).
                                    Major industrial sectors include: food processing, machinery manufacturing, petroleum extraction, shipbuilding, cement, electronics, chemicals, metallurgy, pharmaceuticals, textiles, furniture, tobacco, paper, and printing equipment. Over 60% of products are exported, accounting for about 70% of total exports. Products such as marine engines, cement equipment, hearing aids, enzyme preparations, and synthetic insulin are world-renowned.
                                    The service industry is well-developed, accounting for about 62.82% of GDP (2022). It mainly includes commerce, telecommunications, finance, insurance, tourism, and technical services. Tourism is an important industry within the Danish service sector.
                                    Automotive industry: Denmark has some car manufacturers specializing in specific fields, such as Zenvo, a Danish supercar manufacturer established in 2004, focusing on the design and production of high-performance sports cars. Hydrema is a heavy vehicle manufacturer mainly producing excavators, dump trucks, and other engineering vehicles. Additionally, Denmark's automotive industry primarily focuses on component manufacturing and technological R&D rather than complete vehicle production.
                                    Denmark has several automotive component suppliers specializing in the R&D and production of aluminum parts, exhaust systems, air conditioning systems, etc. For example, Danfoss and Hydro Alunova collaborate on developing eco-friendly automotive air conditioning systems. Technical joint ventures: Denmark's automotive industry is known for its technical joint ventures, driving technological innovation and product upgrades through collaborations with globally renowned companies.
                                    The Danish automotive industry directly provides about 5,400 jobs, with an indirect impact of 27,000. Denmark has several automotive industry clusters, such as the Hydro aluminum industry cluster in Southern Jutland, which provides aluminum automotive parts and design services. Dinex, a leading supplier of automotive aftermarket exhaust systems and control systems in Europe, is part of this cluster, developing advanced exhaust filter technologies. However, fierce competition from low-cost Chinese electric vehicles may severely impact the domestic automotive component industry. Some component manufacturers, such as Dinex, may be phased out by electric vehicles.
                                    The Danish Prime Minister emphasized the importance of reducing Europe's dependence on Chinese products. The Data Protection Agency highlighted serious data security risks associated with Chinese-made electric vehicles.
                                    Pork industry: Danish pork exports hold a significant position in the global market, with an export share of about 7.3%. The primary consumption regions for Danish pork remain within the EU, with major markets including Germany, the UK, Poland, China, Japan, Italy, and Sweden.
                                   In Q2 2022, Denmark's GDP was €96,381.4 million, with slight fluctuations between quarters. By Q3 2023, it dropped to €91,420.0 million but rebounded to €98,996.4 million by Q3 2024, showing some growth momentum.Denmark exhibits a high level of structural dependence on rare earth elements, primarily driven by its wind turbine production.""",
        "X_political (Domestic Politics and Interest Mediation)": """Denmark's political stability index is as high as 8.55, making it a highly stable country. Denmark ranks among the top globally in government efficiency, rule of law, corruption control, and social welfare systems, regarded as one of the most stable countries with minimal social and political conflicts. In December 2022, the Social Democrats, Liberal Party, and Moderate Party formed a cross-camp coalition government, focusing on economic, welfare reform, green policies, and foreign affairs.
                                        Key initiatives include introducing inflation relief measures, optimizing the tax structure; reducing emissions by 110% from 1990 levels by 2050, achieving carbon neutrality by 2045; improving the national welfare system, advancing public sector, education, and healthcare reforms, optimizing early retirement systems; and campaigning for the 2025-2026 UN Security Council non-permanent seat (already elected).""",
        "X_institutional (Institutions, Diplomacy, and Path Dependence)": """Denmark is relatively supportive of globalization and free trade.Denmark recognized the new China on January 9, 1950, and established diplomatic relations with the new China on May 11, 1950, becoming the second Western country to do so. On February 15, 1956, both countries upgraded their legations to embassies and exchanged ambassadors. In the 1950s, Denmark supported the restoration of China's legitimate seat in the United Nations. From the 1960s to the 1970s, interactions between the two countries increased.
                                     According to international organization forecasts, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025. Despite slowing growth, global trade is generally on an upward trend. Italy plays an important role in international trade, particularly in luxury goods, machinery, and food.
                                   Denmark views the EU and NATO as the pillars of its foreign policy, actively expanding Baltic Sea cooperation based on Nordic collaboration. It actively promotes 'green diplomacy' and supports the Paris Agreement on climate change. Denmark considers the EU the core of its foreign policy, supporting the EU in playing a greater role in international affairs. Denmark emphasizes multilateralism and international cooperation, viewing the EU as an important platform for addressing global challenges such as climate change, migration crises, and security issues.
                                   Denmark's main export partners include: Germany: 16% of total exports, Sweden: 10% of total exports, the UK, the Netherlands, and France: each 8% of total exports, Norway: 6% of total exports, the USA: 5% of total exports, China: 4% of total exports. Denmark has a low dependency on China.
                                China's main imports from Denmark include transportation equipment, telecommunications products, paper, crude oil, coal, steel, machinery, and feed.
                                Denmark’s FDI to China was 59.51 billion Dolor in 2023 and 701.64 billion in 2024; China’s FDI to Denmark amounted to 4.94 billion in 2023 and 2.03 billion in 2024.Joint ventures include Shanghai Tielong Multimodal Transport Co., Ltd., Carlsberg Brewery (Sichuan) Co., Ltd., and Hubei Dinex-Tongda Emission Control Systems Co., Ltd., among others.""",
},
    "Ireland": {
        "country_name": "Ireland",
        "population": 5271000,
        "X_market (Market / Economic Interdependence)": """
            【Population】5.2714 million (December 2023). Catholics account for 74.6%, with the remainder primarily adhering to Protestantism. Ireland's traditional economy is based on agriculture and animal husbandry. Following the 2008 global financial crisis, Ireland became one of the first European countries to experience an economic recession. In 2010, it fell into a sovereign debt crisis, accepting an €85 billion bailout from the EU and the International Monetary Fund (IMF) while implementing strict fiscal austerity measures. In 2011, Ireland was the first among heavily indebted EU countries to resume economic growth, and in December 2013, it announced an unconditional exit from the EU, European Central Bank, and IMF aid program.
            In 2021, Ireland's GDP grew by 13.5% year-on-year, making it the fastest-growing economy in Europe that year. In 2022, it maintained high growth at 9.4%. However, in 2023, the economy declined, with a GDP of €466.2 billion, a year-on-year decrease of 1.9%. 【Industry】Key sectors include electronics, telecommunications, chemicals, pharmaceuticals, machinery manufacturing, mining, textiles, clothing, leather, paper, printing, food processing, and wood processing. In recent years, industries such as chemicals, electronic engineering, and computer software have advanced rapidly, while traditional sectors like clothing, footwear, and leather have seen a significant decline in their share.
            Automotive Industry: Ireland has a relatively complete automotive industry chain, covering multiple stages from parts production, vehicle assembly to sales and services. International automotive manufacturers such as Jaguar Land Rover and Volkswagen Group have production bases in Ireland, attracting numerous parts suppliers and service providers, forming a well-developed industrial cluster. Parts Production: Ireland has strong competitiveness in automotive parts, particularly in electronic control units (ECUs), sensors, and battery technology.
            With the acceleration of electrification and intelligent trends, Irish parts companies are transitioning to high-value-added areas.  According to the Central Statistics Office (CSO) of Ireland, the automotive manufacturing industry directly employs approximately 10,000 people. In 2019, the output value of Ireland's automotive parts manufacturing industry reached €1.5 billion. The main export destinations for Ireland's automotive industry are the UK and other EU countries. The Irish automotive industry chain is primarily focused on traditional fuel vehicles, and its export scale is relatively limited, far below its core export categories such as pharmaceuticals and chemicals (e.g., pharmaceutical exports accounted for 35.5% of total exports in 2021). Additionally, as a trading partner of Ireland, China's cooperation focuses on pharmaceuticals, technology, and other fields, with automotive trade not being a primary direction.
            Dairy Industry: Based on the most recent data available, Ireland is a significant exporter of dairy products, particularly cheese and curd. The United Kingdom is a major destination for Irish dairy exports, with Ireland being the leading EU destination for UK cheese and curd exports in 2024. Approximately £86.09 million worth of cheese and curd were exported to Ireland in the 12 months ending June 2024. In terms of volume, Ireland received around 22,432 metric tons of cheese and curd exports from the UK in the same period. It's clear that there is a strong trade relationship with the UK in the dairy sector. The Irish dairy market is projected to grow, with the milk market expected to reach US$307.22 million in 2024 and show an annual growth rate of 3.03% (CAGR 2024-2029).
           In the second quarter of 2022, Ireland's GDP was €125,474.8 million, rising to €138,568.7 million in the third quarter of 2022, followed by fluctuations, reaching €129,967.2 million in the third quarter of 2023. In the third quarter of 2024, GDP rebounded to €137,795.5 million. Overall, the economy shows cyclical fluctuations but tends toward stability.""",
        "X_political (Domestic Politics and Interest Mediation)": """Ireland's political stability index is 7.85, classifying it as a highly stable country. Despite historical social conflicts, the political environment has remained stable in recent years, with good corruption control, sustained economic development, and an overall positive social trend.""",
        "X_institutional (Institutions, Diplomacy, and Path Dependence)": """Ireland emphasizes that Russia’s actions threaten European security but maintains a relatively moderate defense posture compared to Nordic or Eastern European countries.Ireland established diplomatic relations with China on June 22, 1979. Following the 2008 global financial crisis, Ireland became one of the first European countries to experience an economic recession. In 2010, it fell into a sovereign debt crisis, accepting an €85 billion bailout from the EU and the IMF while implementing strict fiscal austerity measures. In 2011, Ireland was the first among heavily indebted EU countries to resume economic growth.
         According to international organization forecasts, global trade is expected to grow by 2.7% in 2024 and 3.0% in 2025. Despite slowing growth, global trade overall shows an upward trend. Italy plays an important role in international trade, particularly in luxury goods, machinery, and food.
       Ireland's policies on climate change and emission reduction targets are highly consistent with EU directives. Additionally, Ireland has shown strong consistency in supporting EU aid to Ukraine and economic sanctions, with support rates of 86% and 84%, respectively. EU funding and policy support have helped Ireland achieve economic modernization, particularly in attracting foreign investment and developing technology and pharmaceutical industries. Over one-third of Ireland's exports go to the EU market, while the EU is also a significant source of imports. As part of the EU single market, Ireland provides businesses with access to a market of 450 million consumers.
   On June 22, 1979, China and Ireland signed the Joint Communiqué on the Establishment of Diplomatic Relations, and in 1980, the two countries exchanged ambassadors. Since the establishment of diplomatic ties, bilateral relations between China and Ireland have developed rapidly. The Irish government formulated the Asia Strategy in 1998 and a new phase of the Asia Strategy in 2005. In 2020, it launched the Global Strategy for Asia-Pacific 2025, identifying China as a key partner for Ireland in the Asian region.Sino-Irish economic and trade cooperation has developed rapidly in recent years. China is Ireland's fourth-largest global trading partner. Ireland has maintained a trade surplus with China for many years, primarily concentrated in pharmaceuticals and technology. The trade volume between Ireland and China was €25.409 billion in 2022 and €17.583 billion in 2023, a year-on-year decrease of 30.80%. From January to September 2024, bilateral trade between China and Ireland reached $17.91 billion, a year-on-year increase of 13.1%, with Chinese exports at $3.78 billion (up 17.7%) and imports at $14.13 billion (up 11.9%). Ireland joined the Asian Infrastructure Investment Bank in March 2017. In April 2024, Ireland served as the Guest Country of Honor at the 4th China International Consumer Products Expo.
    Ireland’s FDI to China was -1542.29 billion Dolor in 2023 and -1542.29 billion in 2024; China’s FDI to Ireland amounted to 19.41 billion in 2023 and 1661.77 billion in 2024.Joint ventures include Shanghai Hefeng Pharmaceutical Co., Ltd., Huawei Technologies (Ireland) Co., Ltd., and Tencent’s Ireland data center, among others.""",
},
"Lithuania": {
    "country_name": "Lithuania",
    "population": 2830144,
    "X_market (Market / Economic Interdependence)": """Industrial Structure and Export Orientation：
     Lithuania’s main export products include mineral products, foodstuffs, beverages, tobacco and tobacco products, chemical products, and plastic products. Its main import products consist of crude oil, automobiles, petroleum gas, machinery, and electrical equipment."From January to August 2025, Lithuania’s primary export destinations were Latvia (12.4%), Poland (10.4%), and Germany (9.1%). Its main import partners were Poland (13.8%), Germany (12.8%), and Latvia (8.3%)."
        Automotive Industry’s Share of GDP and Employment
        Five months into the year, demand for new commercial vehicles in the European Union declined by 36.7%, following three consecutive months of steep decreases. All 27 EU markets recorded double-digit declines, with Lithuania experiencing one of the largest contractions (-55.7%).
        In May 2020, new heavy truck registrations fell by 59.7% to 11,783 units across the EU. Central European markets were particularly affected (-74.5%), with Estonia, Lithuania, Bulgaria, and Hungary each recording declines of over 80%. This indicates the relatively limited scale and high vulnerability of Lithuania’s automotive market.
          Macroeconomic Indicators
             In 2024, Lithuania’s key economic indicators were as follows:
              Gross Domestic Product (GDP): €78.41 billion
           GDP per capita: €27,150
             GDP growth rate: 2.8%
              Unemployment rate: 7.1%
              In 2023, Germany and Poland were Lithuania’s most important import partners, each accounting for approximately 13% of total imports.""",
    "X_political (Domestic Politics and Interest Mediation)":""" Political Stability and Party System
Lithuania’s domestic political situation is generally stable. In the parliamentary elections held in October 2024, six political parties, including the Social Democratic Party, entered parliament.
In September 2025, a new government was formed, composed of the Social Democratic Party, the Nemunas Dawn Party, the Farmers and Greens Union, and the Christian Family Alliance. The coalition reflects a relatively broad political base, contributing to institutional stability but also requiring consensus-building among parties with diverse policy preferences.""",
    "X_institutional (Institutions, Diplomacy, and Path Dependence)": """ As a country near the frontline of the Russia-Ukraine conflict, the Lithuanian government has taken a firm stance by treating Russia as a direct threat and announcing a significant increase in defense spending to address regional security risks. Lithuania has become one of the most steadfast supporters of Ukraine within the EU and NATO. Lithuania has raised its defense expenditure to 5–6% of its GDP. EU and NATO Membership
            Lithuania joined NATO on March 29, 2004, and acceded to the European Union on May 1, 2004, anchoring its foreign and security policy firmly within Euro-Atlantic institutions.
            Historical Diplomatic Relations with China
              On September 14, 1991, China and Lithuania officially established diplomatic relations through the signing of the Joint Communiqué on the Establishment of Diplomatic Relations between the People’s Republic of China and the Republic of Lithuania.
                High-level exchanges occurred intermittently in the following years. In November 2015, Lithuanian Prime Minister Algirdas Butkevičius visited China to attend the Fourth China–Central and Eastern European Countries Leaders’ Meeting. In March 2016, he attended the Boao Forum for Asia Annual Conference. In November 2018, Lithuanian President Dalia Grybauskaitė participated in the First China International Import Expo in Shanghai.
            Institutional Rupture and Diplomatic Downgrading
                In November 2021, Lithuania approved the establishment of a so-called “Taiwanese Representative Office in Lithuania.” In response, China announced the downgrading of bilateral diplomatic relations to the chargé d’affaires level.
                China banned imports of dairy products, peat, and any products labeled “Made in Lithuania” from Lithuania.
                Since then, there have been no high-level official exchanges between China and Lithuania, and bilateral cooperation across political, economic, and cultural fields has remained limited.
                Lithuania’s FDI to China was 1.32 billion Dolor in 2023 and -1.32 billion in 2024; China’s FDI to Lithuania amounted to 19.94 billion in 2023 and 24.05 billion in 2024. Joint ventures include Avia Leasing (China) Co., Ltd. and Zhonglong O-Fly Aircraft Maintenance Engineering Co., Ltd., among others.""",
},
}
